apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-app1
spec:
  rules:
  - host: "python-app1.test.com"
    http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: python-app1
              port:
                number: 8080
